# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_bookinfo_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userPasswd', models.CharField(max_length=50)),
            ],
        ),
    ]
