# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=500)),
                ('bookID', models.CharField(max_length=50)),
            ],
        ),
    ]
