# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=50)),
                ('bookName', models.CharField(max_length=300)),
                ('bookDetail', models.CharField(max_length=3000)),
                ('imgUrl', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
    ]
