# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bookIntro',
            field=models.CharField(default='', max_length=300),
        ),
    ]
